skalliBundle\Entity\Test:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        jilali:
            type: text
        juuu:
            type: text
        hu:
            type: datetime
    lifecycleCallbacks: {  }
